# Generated by Django 3.1.3 on 2021-06-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(max_length=3, primary_key=True, serialize=False, verbose_name='题号')),
                ('content', models.CharField(default='', max_length=200, verbose_name='内容')),
                ('is_reverse', models.BooleanField(default=False, verbose_name='选项是否反向')),
            ],
            options={
                'verbose_name': '题目信息',
                'verbose_name_plural': '题目信息',
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=30, verbose_name='地址')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(max_length=6, primary_key=True, serialize=False, verbose_name='编号')),
                ('times', models.IntegerField(max_length=10, verbose_name='测试次数')),
                ('option', models.CharField(max_length=1, verbose_name='选项')),
                ('tproblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate_test.problem', verbose_name='题目')),
                ('tuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate_test.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题信息',
                'verbose_name_plural': '答题信息',
                'db_table': 'record',
            },
        ),
    ]
