# Generated by Django 3.1.3 on 2021-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate_test', '0006_auto_20210607_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='得分'),
        ),
    ]
